###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "userName": "asd",
  "userEmail": "asd@asd.hu",
  "userPassword": "titkos123"
}


###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "admin@admin.hu",
  "password": "titkos123"
}
###
POST http://localhost:3001/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjIsImVtYWlsIjoiYXNkQGFzZC5odSIsInVzZXJQZXJtaXNzaW9ucyI6W119LCJpYXQiOjE3MTIxMzYxMTUsImV4cCI6MTcxNDcyODExNX0.v3k_Q1FtabFxa4z6TQoOBnKgQyumsokgvungpE8ia80
Content-Type: application/json

{
  "transOrigin": "Dánszentmiklós Altár út 23",
  "transTarget": "Pécs Kút utca 6",
  "itemId": 1,
  "warehouseId": 2
}

###
PATCH http://localhost:3001/warehouses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uaHUiLCJ1c2VyUGVybWlzc2lvbnMiOlt7InBlcm1pc3Npb25OYW1lIjoiQWxsIn1dfSwiaWF0IjoxNzEyNzQxNDA2LCJleHAiOjE3MTUzMzM0MDZ9.H143-dd9adQ1Uf25ZP2dNMBeyIHT_SvrQnqgMxgMIKg
Content-Type: application/json

{
  "warehouseId": 3,
  "warehouseLocation": "Temető"
}