###
POST http://localhost:3001/user/login
Content-Type: application/json

{
  "user_email": "jhon.doe@teszt.hu",
  "user_password": "titkos123"
}

###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "email": "jhon.doe@teszt.hu",
  "password": "titkos123",
  "name": "Jhon Doe"
}

###
POST http://localhost:3001/user/update
Content-Type: application/json

{
  "data": {
    "user_email": "jhone.done@teszt.hu"
  },
  "where": 2
}

###
POST http://localhost:3001/roles/userRole
Content-Type: application/json

{
  "user_id": 1
}
###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "jhon.doe@teszt.hu",
  "password": "titkos123"
}

###
GET http://localhost:3001/auth/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjF9LCJlbWFpbCI6Impob24uZG9lQHRlc3p0Lmh1IiwiaWF0IjoxNzA5NzE5MzMwLCJleHAiOjE3MTIzMTEzMzB9.-MCyUFaLKHQgqW8H90MNg0D5ytBE6XyokZynzeCDqt4

###
POST http://localhost:3001/transactions/newTrans
Content-Type: application/json

{
  "trans_post_date": "2024.03.26",
  "trans_origin": "Innen",
  "trans_target": "Oda",
  "warehouse_warehouse_id": 1,
  "item_item_id": 1
}